### ISSUE TITLE
Perforamce Bug

### ISSUE THREAD

**Issue by miladrahimi** [amirrezaask/JasVim#1]
Use `rm -rf` command and delete this tool, then choose a JetBrains IDE based on your language, use it, enjoy it, and focus on your application logic instead.

**Comment by amirrezaask** [comment]
Some people prefer ready to use tools like Jetbrains
Some people prefer customizable tools like vim, neovim or Emacs
and some people like are passionate about creating tools for other developers
for me my application logic is the tool itself.
It's no fight use whatever tool that makes you happy
